blog/urls.py
from django.urls import path
from . import views

app_name="blog"
urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('post/<int:pk>/', views.Perma.as_view(), name='onepost'),
    path('post/delete/<int:pk>/', views.PostDelete.as_view(), name='deletepost'),
    path('post/newpost/', views.NewPost.as_view(), name='newpost'),
    path('post/comment/', views.comments, name='cmnt'),
    path('post/comments/', views.AllComments, name='cmntes'),
    path('post/like/', views.PostLike, name='like'),
    path('signup/', views.Signup.as_view(), name='signup'),
    path('login/', views.Login.as_view(), name='login'),
    path('user/editprofile/', views.EditProfile.as_view(), name='editprofile'),
    path('user/editpass/', views.EditPassword.as_view(), name='editpass'),
    path('user/profile/', views.Profile.as_view(), name='profile'),
    path('dataa', views.FacebookData.as_view(), name='facebookdata'),
    
]

portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib.auth.models import User

class Post(models.Model):
	sno = models.AutoField(primary_key = True)
	author= models.ForeignKey(User, on_delete=models.CASCADE)
	title= models.TextField()
	content=models.TextField()
	likes=models.ManyToManyField(User, related_name='likes')
	create_date=models.DateTimeField(auto_now_add= True)

	def __str__(self):
		return self.title

	def datecreated(self):
		return self.create_date.strftime('%d %b, %Y')

	def Content(self):
		return self.content[:200]+"..."

	def Contents(self):
		return self.content[:100]+"..."

	def total_likes(self):
		return self.likes.count()


class Comment(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE)
	post=models.ForeignKey(Post, on_delete=models.CASCADE)
	msg=models.TextField()
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.msg

blog/forms.py
from django import forms
from .models import Post, Comment
from datetime import datetime
from django.contrib.auth.models import User
class NewpostForm(forms.ModelForm):
	class Meta:
		model= Post
		fields=['title', 'content']

class SignupForm(forms.ModelForm):
	vpass=forms.CharField(max_length=70)
	class Meta:
		model=User
		fields=['username', 'first_name', 'last_name', 'email','password']


class EditProfileForm(forms.ModelForm):
	class Meta:
		model=User
		fields=['username', 'first_name', 'last_name', 'email']


class EditPasswordForm(forms.ModelForm):
	vpass=forms.CharField(max_length=70)
	newpass=forms.CharField(max_length=70)
	class Meta:
		model=User
		fields=['password']


class CommentForm(forms.ModelForm):
	class Meta:
		model=Comment
		fields=['msg']

blog/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from .models import Post, Comment
from django.views.generic import TemplateView, DetailView
from .forms import NewpostForm, SignupForm, EditProfileForm, EditPasswordForm, CommentForm
from django.utils import timezone
from datetime import datetime
import urllib3
import json
import random
import hashlib
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.contrib.auth import logout, login, authenticate
import os



class HomePage(TemplateView):
	def get(self, request):
		posts= Post.objects.all().order_by('create_date').reverse()
		return render(request, 'blog/front.html', {'alldata':posts})


class NewPost(TemplateView):
	def get(self,request):
		bg=NewpostForm(request.GET)
		user=None
		user=request.user
		if user.is_authenticated:
			return render(request,"blog/newpost.html",{'user':user})
		else:
			return redirect(reverse('blog:signup',))

	def post(self, request):
		bg=NewpostForm(request.POST)
		if bg.is_valid():
			author=request.user
			title= bg.cleaned_data['title']
			content=bg.cleaned_data['content']
			content=content.replace('\n', '<br>')
			p=Post(title= title, content=content,author= author)
			p.save()
			return redirect(reverse('blog:onepost',args=(p.pk,)))
		else:
			title= bg.cleaned_data['title']
			content=bg.cleaned_data['content']
			return render(request, 'blog/newpost.html',{'title': title, 'content':content})


class Perma(TemplateView):
	def get(self,request, pk):
		post= Post.objects.filter(pk=pk).first()
		cmnts=Comment.objects.filter(post=post).first()
		if cmnts:
			cmnts=True
		user=request.user
		if user.is_authenticated:
			like=post.likes.filter(id=user.id).first()
			if like:
				like="Unlike"
			else:
				like="Like"
			
			delete=False
			if user==post.author:
				delete=True
			return render(request, "blog/perma.html",{'post':post,'cmnts':cmnts, 'like':like, 'delete': delete})
		else:
			return render(request, "blog/perma.html",{'post':post})


class PostDelete(TemplateView):
	def get(self,request, pk):
		post= Post.objects.filter(pk=pk).first()
		user=request.user
		if user.is_authenticated and user==post.author:
			post.delete()
		return redirect(reverse('blog:home',))
		
	

@csrf_exempt
def comments(request):
	if request.method== 'POST':
		user=None
		user=request.user
		if user.is_authenticated:
			postid=request.POST['postid']
			msg=request.POST['msg']
			if len(msg)>0:
				post= Post.objects.filter(pk=postid).first()
				cmt=Comment(user=user,post=post,msg=msg)
				cmt.save()
			response={'reply':1,}
			return JsonResponse(response,)
		response={'reply':0,}
		return JsonResponse(response,)


@csrf_exempt
def PostLike(request):
	if request.method== 'POST':
		user=request.user
		if user.is_authenticated:
			postid=request.POST['post_id']
			post= Post.objects.filter(pk=postid).first()
			if post.likes.filter(id=user.id).first():
				post.likes.remove(user)
				msg="Like"
			else:	
				post.likes.add(user)
				msg="Unlike"
			response={'like_count': post.total_likes(), 'msg':msg,}
			return JsonResponse(response,)
		response={}
		return JsonResponse(response,)


def AllComments(request):
	if request.method== 'GET':
		postid=request.GET['postid']
		post=Post.objects.filter(id=postid).first()
		allcmnts= Comment.objects.filter(post=post)
		alldata=[]
		for cmnt in allcmnts:
			x=[]
			s=cmnt.user.first_name
			s=s+" " + cmnt.user.last_name
			x.append(s)
			x.append(cmnt.msg)
			alldata.append(x)
		return JsonResponse(alldata,safe=False)


class Profile(TemplateView):
	def get(self,request):
		user=None
		user=request.user
		if user.is_authenticated:
			posts=Post.objects.filter(author=user.id)
			return render(request, "blog/profile.html",{'user':user,'posts':posts})
		else:
			return redirect(reverse('blog:signup',))


class EditProfile(TemplateView):
	def get(self,request):
		sig=EditProfileForm(request.GET)
		user=None
		user=request.user
		dic={}
		if user.is_authenticated:
			dic['username']=user.username
			dic['email']=user.email
			dic['first_name']=user.first_name
			dic['last_name']=user.last_name
			return render(request,"blog/edit_profile.html",dic)
		else:
			return redirect(reverse('blog:signup',))

	def post(self, request):
		user=request.user
		sig=EditProfileForm(request.POST, instance=user)
		if sig.is_valid():
			username=sig.cleaned_data['username']
			first_name=sig.cleaned_data['first_name']
			last_name=sig.cleaned_data['last_name']
			email=sig.cleaned_data['email']
			user=request.user
			if user.is_authenticated:
				user.username=username
				user.first_name= first_name
				user.last_name= last_name
				user.email=email
				user.save()
			return redirect(reverse('blog:profile',))
		
		else:
			return render(request,"blog/edit_profile.html",)	


class EditPassword(TemplateView):
	def get(self,request):
		sig=EditPasswordForm(request.GET)
		user=None
		user=request.user
		dic={}
		if user.is_authenticated:
			return render(request,"blog/edit_pass.html",)
		else:
			return redirect(reverse('blog:signup',))

	def post(self, request):
		user=request.user
		sig=EditPasswordForm(request.POST, instance=user)
		if sig.is_valid():
			user=request.user
			password=sig.cleaned_data['password']
			newpass=sig.cleaned_data['newpass']
			vpass=sig.cleaned_data['vpass']
			dic={}
			if user.password!=password:
				dic['error_password']="Wrong Password!!!!!!"
			if newpass!= vpass:
				dic['error_vpass']="Password not match!!!!!!"
			
			if not dic:
				user.password=newpass
				user.save()
				return redirect(reverse('blog:profile',))
			else:
				return render(request,'blog/edit_pass.html',dic)
			
		else:
			return render(request,'blog/edit_pass.html',)	



fbid = os.environ.get('fbid')

class Login(TemplateView):
	def get(self, request):
		logout(request)
		return render(request,"blog/login.html",{'id':fbid})

	def post(self, request):
		username= request.POST['username']
		password= request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			login(request, user)
			return redirect(reverse('blog:home',))
		else:
			dic={'username':username,'error_password':"Username or Password not matcheds"}
			return render(request,"blog/login.html",dic)


class Signup(TemplateView):
	def get(self,request):
		sig=SignupForm(request.GET)
		logout(request)
		return render(request,"blog/signup.html",{'id':fbid})

	def post(self, request):
		sig=SignupForm(request.POST)
		if sig.is_valid():
			username= sig.cleaned_data['username']
			first_name=sig.cleaned_data['first_name']
			last_name=sig.cleaned_data['last_name']
			email=sig.cleaned_data['email']
			password=sig.cleaned_data['password']
			vpass=sig.cleaned_data['vpass']
			dic={}
			if password != vpass:
				dic['error_vpass']="Password not matched"
			if (User.objects.filter(username=username).first()):
				dic['error_username']="This username already exist"
			if (User.objects.filter(email=email).first()):
				dic['error_email']="This email already exist"

			if dic:
				dic['username']=username
				dic['first_name']=first_name
				dic['last_name']=last_name
				dic['email']=email
				return render(request,'blog/signup.html',dic)
			else:
				p=User.objects.create_user(username=username, first_name=first_name,last_name=last_name, email= email, password=password)
				login(request, p)
				return redirect(reverse('blog:home',))
		else:
			return render(request,'blog/signup.html',)	


class FacebookData(TemplateView):
	def get(self, request):
		fbscurekey= os.environ.get('fbscurekey')
		URL= 'https://graph.facebook.com/v6.0/oauth/access_token?client_id=%s&redirect_uri=https://uploadsomethinks.herokuapp.com/dataa&client_secret=%s&code='%(fbid,fbscurekey)
		URL2="https://graph.facebook.com/me?access_token="
		code=request.GET['code']
		code=URL+str(code)
		lib = urllib3.PoolManager()
		r = lib.request('GET', code)
		data=json.loads(r.data.decode('utf-8'))
		token= str(data["access_token"])
		URL2= URL2+(token)+"&fields=id,name"
		rr= lib.request('GET', URL2)
		data2= json.loads(rr.data.decode('utf-8'))
		username= str(data2['id'])
		if not username:
			return redirect(reverse('blog:signup',))
		name= str(data2['name'])
		password=username
		obj= User.objects.filter(username=username).first()
		if not obj:
			name=list(name.split(' '))
			obj= User.objects.create_user(username=username, first_name=name[0],last_name=name[1], email="", password=password)
		login(request, obj)
		return redirect(reverse('blog:home',))

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'blog/font-awesome.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'blog/font-awesome.min.css' %}">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'blog/util.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
  <title>Blog</title>
</head>
<body>
  <div class="header">
    <div class="newp">
      <a href="{% url 'blog:newpost' %}" class="pctive" >New Blog</a>
    </div>
    <div class="header-right">
      <a href="{% url 'blog:home' %}" class="active" >Home</a>
      {% if user %}
        <a href="{% url 'blog:profile' %}" class="margn-rgt margn-lft">{{user.name}}</a>
        <a href="{% url 'blog:signup' %}">Logout</a>
      {% else %}
        <a href="{% url 'blog:login' %}" class="margn-rgt margn-lft">Login</a>
        <a href="{% url 'blog:signup' %}">Signup</a>
      {% endif %}
    </div>
  </div>
  <div>
  {% block content %}
  {% endblock %}
  </div>
</body>
</html>

blog/templates/blog/edit_pass.html
{% extends 'blog/edit_profile.html' %}
{% load static %}
{% block title %}
  <title>Editpassword</title>
{% endblock %}
{% block content %}    
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
            <form class="login100-form validate-form flex-sb flex-w" method="post">
                {% csrf_token %}
                <span class="login100-form-title p-b-53">
                    Edit Password
                </span>
                
                <div class="p-t-10 p-b-5 wid">
                    <span class="txt1">
                        Current Password
                    </span>
                </div>
                <div class="wrap-input100">
                    <input class="input100" type="password" name="password" required>
                    <span class="focus-input100"></span>
                </div>
                <div  class="error">
                    {{error_password}}
                </div>
                <div class="p-t-10 p-b-5 wid">
                    <span class="txt1">
                        New Password
                    </span>
                </div>
                <div class="wrap-input100 ">
                    <input class="input100" type="password" name="newpass" required >
                    <span class="focus-input100"></span>
                </div>

                <div class="p-t-10 p-b-5 wid">
                    <div class="txt1">
                        Verify Password
                    </div>
                </div>
                <div class="wrap-input100">
                    <input class="input100" type="password" name="vpass" required >
                    <span class="focus-input100"></span>
                </div>
                <div  class="error">
                    {{error_vpass}}
                </div>
                
                <br>
                <div class="container-login100-form-btn m-t-17">
                    <button class="login100-form-btn" type="submit">
                        Submit
                    </button>
                </div>
                <div class="w-full text-center p-t-55">
                    <span class="txt2">
                        Want to Edit Profile...
                    </span>

                    <a href="{% url 'blog:editprofile' %}" class="txt2 bo1">
                        Click here!!!
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/edit_profile.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    {% block title %}
      <title>Editprofile</title>
    {% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'blog/bootstrap.min.css' %}">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'blog/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/mainl.css'  %}">
<!--===============================================================================================-->

</head>
<body>
<div class="header">
    <a href="{% url 'blog:newpost' %}" class="pctive" >New Blog</a>
        <div class="header-right">
          <a href= "{% url 'blog:home' %}">Home</a>
          {% if request.user.is_authenticated %}
            <a class="margn-rgt margn-lft" href="{% url 'blog:profile' %}">Profile</a>
            <a href="{% url 'blog:signup' %}">Logout</a>
          {% else %}
            <a href="{% url 'blog:login' %}" class="margn-rgt margn-lft">Login</a>
            <a href="{% url 'blog:signup' %}">Signup</a>
          {% endif %}
        </div>
    </div>
{% block content %}
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
                <form class="login100-form validate-form flex-sb flex-w" method="post">
                    {% csrf_token %}
                    <span class="login100-form-title p-b-53">
                        Edit Profile
                    </span>
                    
                    <div class="p-t-10 p-b-5 wid">
                        <span class="txt1">
                            Username
                        </span>
                    </div>
                    <div class="wrap-input100">
                        <input class="input100" type="text" name="username" value="{{username}}">
                        <span class="focus-input100"></span>
                    </div>
                    <div class="p-t-10 p-b-5 wid">
                        <span class="txt1">
                            First Name
                        </span>
                    </div>
                    <div class="wrap-input100 ">
                        <input class="input100" type="text" name="first_name" required value="{{first_name}}">
                        <span class="focus-input100"></span>
                    </div>

                    <div class="p-t-10 p-b-5 wid">
                        <span class="txt1">
                            Last Name
                        </span>
                    </div>
                    <div class="wrap-input100 ">
                        <input class="input100" type="text" name="last_name" required value="{{last_name}}">
                        <span class="focus-input100"></span>
                    </div>

                    <div class="p-t-10 p-b-5 wid">
                        <div class="txt1">
                            Email
                        </div>
                    </div>
                    <div class="wrap-input100">
                        <input class="input100" type="text" name="email" required value="{{email}}">
                        <span class="focus-input100"></span>
                    </div>
                    <div  class="error">
                        {{error_email}}
                    </div>
                    
                    <br>
                    <div class="container-login100-form-btn m-t-17">
                        <button class="login100-form-btn" type="submit">
                            Submit
                        </button>
                    </div>
                    <div class="w-full text-center p-t-55">
                        <span class="txt2">
                            Do you want to change Password?
                        </span>

                        <a href="{% url 'blog:editpass' %}" class="txt2 bo1">
                            Click here!!
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

blog/templates/blog/front.html
{% extends 'blog/home.html' %}
{% block content %}
{% load static %}
<div class="limiter">
<div class="container-login100">
	<div class="wrap-contact101">	
		<form action="" >
			{% for p in alldata %}
			    <span >
				  <a href="{% url 'blog:onepost' p.pk %}"
				    class="contact101-form-title"
				   style="text-decoration: none">{{p.title | safe}}</a>
				</span>
				<span class="label-input101">
					{{p.datecreated}}
				</span>
				<div class="wrap-input100" >
				  <div >
				    {{p.Content | safe}}
				  </div>
				</div>
				<br>
			{% endfor %}
		</form>
	</div>
</div>
{% endblock %}

blog/templates/blog/home.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'blog/font-awesome.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'blog/font-awesome.min.css' %}">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'blog/util.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script type="text/javascript" src="{% static 'blog/perma.js' %}"></script>
  {% block title %}
  <title>Blog</title>
  {% endblock %}
</head>
<body>
  <div class="header">
    <div class="newp">
      <a href="{% url 'blog:newpost' %}" class="pctive" >New Blog</a>
    </div>
    {% block del %}
    {% endblock %}
    <div class="header-right">
      <a href="{% url 'blog:home' %}">Home</a>
      {% if request.user.is_authenticated %}
        {% block user_name %}
          <a href="{% url 'blog:profile' %}" class="margn-rgt margn-lft">{{request.user.first_name}}</a>
        {% endblock %} 
        {% block logout %}
        {% endblock %}
      {% else %}
        <a href="{% url 'blog:login' %}" class="margn-rgt margn-lft">Login</a>
        <a href="{% url 'blog:signup' %}">Signup</a>
      {% endif %}
    </div>
  </div>
  {% block content %}
  {% endblock %}
</body>
</html>

blog/templates/blog/perma.html
{% extends 'blog/home.html' %}
{% load static %}
{% block del %}
  {% if delete %}
    <div class="newp">
      <a href="{% url 'blog:deletepost' post.pk%}" class="pctive" >Delete</a>
    </div> 
  {% endif %}
{% endblock %}
{% block content %}
<div class="limiter">
  <div class="container-login100">
  <div class="wrap-contact101">
    {{post.author.first_name}} {{post.author.last_name}}
    </span>
    <span class="label-input100">
    {{post.datecreated}}
    </span>
    <br>
    <span class="contact100-form-title">
        {{post.title | safe }}
    </span>
    <div class="wrap-input100" >
      <div class="">
        {{post.content | safe }}
      </div>
    </div>
    <form method ="post">
    {% csrf_token %}
      <input type="hidden" id="xyz" data-id="{{post.pk}}">
    <div class="wrap-input101" >
      <span class="label-input100">Comment</span>
      <textarea class="input100" id="x2" name="msg" placeholder="Write somethink..." ></textarea>
      <hr>
    </div>
    </form>
    <div class="l-c-section">
      <span class="newp">
        <button id="total_likes">
          {{post.total_likes}}
        </button>
        {% if request.user.is_authenticate %}
          <button type="button" id="like" >{{like}}</button>
        {% else %}
          <button type="button" id="like" >Like</button>
        {% endif %}
      </span>
      <span>
      <button id="comments">Show Comments</button>
    </span>
    </div>
    <div id="tb">
    {% if cmnts %}
      <div id="cmnttable">
      </div>
    {% endif %}
    </div>
  </div>
</div>
</div>
{% endblock %}

blog/templates/blog/profile.html
{% extends 'blog/home.html' %}
{% load static %}
{% block title %}
  <title>Profile</title>
  {% endblock %}
{% block user_name %}
	<a class="margn-rgt margn-lft" href="{% url 'blog:editprofile' %}">Edit Profile</a>
{% endblock %}
{% block logout %}
  <a href="{% url 'blog:signup' %}">Logout</a>
{% endblock %}
{% block content %}
<div class="limiter">
	<div class="container-login100">
	<div class="wrap-contact100">
		<form class="contact100-form">
			<h1><b>
				{{user.first_name}} {{user.last_name}}
			</b></h1>
			<br>
			<span class="contact100-form-title">Genral Details-</span>
			<div >
			  Username: {{user.username}}	
			</div>
			{% if user.email %}
			<div>
				Email: {{user.email}}
			</div>
			{% endif %}
			{% for p in posts %}
			    <span class="contact100-form-title">Posts:</span>
			    <span >
					<a href="{% url 'blog:onepost' p.pk %}"
					    class="contact100-form-title"
					    style="text-decoration: none">{{p.title | safe}}
					</a>
				</span>
				<span class="label-input101">
					{{p.datecreated}}
				</span>
				<div class="wrap-input100" >
				  <div >
				    {{p.Contents | safe}}
				  </div>
				</div>
				<br>
			{% endfor %}
		</form>
	</div>
</div>
</div>
{% endblock %}

blog/templates/blog/signup.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    {% block title %}
      <title>Signup</title>
    {% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'blog/bootstrap.min.css' %}">
<!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'blog/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/mainl.css'  %}">
<!--===============================================================================================-->

</head>
<body>
    {% block content %}
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
                <form class="login100-form validate-form flex-sb flex-w" method="post">
                    {% csrf_token %}
                    <span class="login100-form-title p-b-53">
                        Sign Up With
                    </span>
                    
                    <a href='https://www.facebook.com/v6.0/dialog/oauth?client_id={{id}}&redirect_uri=https://uploadsomethinks.herokuapp.com/dataa&' 
                    class="btn-face m-t-15 m-b-15 fb-login-button">
                        <i class="fa fa-facebook-official"></i>
                        Signup with Facebook
                    </a>
                    <div class="p-t-10 p-b-5 wid">
                        <span class="txt1">
                            Username
                        </span>
                    </div>
                    <div class="wrap-input100">
                        <input class="input100" type="text" name="username" required value="{{username}}">
                        <span class="focus-input100"></span>
                    </div>
                    <div class="error">
                            {{error_username}}
                    </div>
                    <div class="p-t-10 p-b-5 wid">
                        <span class="txt1">
                            First Name
                        </span>
                    </div>
                    <div class="wrap-input100 ">
                        <input class="input100" type="text" name="first_name" required value="{{first_name}}">
                        <span class="focus-input100"></span>
                    </div>

                    <div class="p-t-10 p-b-5 wid">
                        <span class="txt1">
                            Last Name
                        </span>
                    </div>
                    <div class="wrap-input100 ">
                        <input class="input100" type="text" name="last_name" required value="{{last_name}}">
                        <span class="focus-input100"></span>
                    </div>


                    <div class="p-t-10 p-b-5 wid">
                        <div class="txt1">
                            Email
                        </div>
                    </div>
                    <div class="wrap-input100">
                        <input class="input100" type="text" name="email" required value="{{email}}">
                        <span class="focus-input100"></span>
                    </div>
                    <div  class="error">
                        {{error_email}}
                    </div>
                    
                    <div class="p-t-10 p-b-5 wid">
                        <span class="txt1">
                            Password
                        </span>
                    </div>

                    <div class="wrap-input100 ">
                        <input class="input100" type="password" name="password" required value="">
                        <span class="focus-input100"></span>
                    </div>

                    <div class="p-t-13 p-b-5">
                        <span class="txt1">
                            Verify Password
                        </span>
                    </div>

                    <div class="wrap-input100">
                        <input class="input100" type="password" name="vpass" required value="">
                        <span class="focus-input100"></span>
                    </div>
                    <div class="error">
                        {{error_password}}
                    </div>
                    <br>
                    <div class="container-login100-form-btn m-t-17">
                        <button class="login100-form-btn" type="submit">
                            Sign Up
                        </button>
                    </div>

                    <div class="w-full text-center p-t-55">
                        <span class="txt2">
                            Already member?
                        </span>

                        <a href="{% url 'blog:login' %}" class="txt2 bo1">
                            Login now
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}
</body>
</html>